### ISSUE TITLE
Err when excute make local-run

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-user#6]
When I try to execute "make local-run" command. I'm getting this error.

```bash
# gorm.io/driver/postgres
/home/sdd/go/pkg/mod/gorm.io/driver/postgres@v1.5.5/migrator.go:411:26: m.GuessConstraintInterfaceAndTable undefined (type Migrator has no field or method GuessConstraintInterfaceAndTable)
make: *** [Makefile:73: local-run] Error 1
```
I check the lib and there is no such method as GuessConstraintInterfaceAndTable the error seems right.

**Comment by Sddilora** [comment]
I realized that the "gorm.io/driver/postgres" verison in our repo is v1.5.2 but somehow somethings cause this "used metadata's version v1.5.5 rather than go.mod's version v1.5.2" .
![image](https://github.com/octoposprime/op-be-user/assets/122971619/6ebe5117-62af-42e7-9eb9-2525b3daebdd)

**Comment by husamettinarabaci** [comment]
Gorm repository owners released a new version with a bug yesterday. I have changed the Postgres dependency version from v1.5.5 to v1.5.2. You must pull all backend projects and run "go clean -modcache". It will run perfectly.

Note: You must pull ALL PROJECTS because someone be able to depend latest version of Postgres on your local.

https://github.com/go-gorm/postgres/actions/runs/7772142248/job/21194228758

**Comment by Sddilora** [comment]
Thank you for providing the solution that resolved the issue.
